const permissions = {
  Login: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Dashboard: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],

  Add_Company: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Add_Contact: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Edit_Contact: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Emails_log_activity_History: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  View_Company_Activities_tab: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Recruiter',
    'Delivery Head',
  ],
  View_Emails_History_tab: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Edit_Company: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  'Delete company': [
    'Admin',
    'Sales Head',
    'Delivery Head',
  ],
  'View company': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Search_company: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Change_Status_Of_A_Company: [
    'Admin',
    'Sales Rep',
    'Sales Head',
  ],
  Log_an_activity_In_Company: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Send_Emails_To_Client_Contacts: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  View_The_Activity_In_Company: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],

  Add_job_opening: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Edit_job_opening: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  'Delete job opening': [
    'Admin',
    'Sales Head',
    'Delivery Head',
  ],
  'View job opening': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Search_job_opening: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  My_openings: [
    'Recruiter',
    'Sales Rep',
    'Delivery Head',
  ],
  All_openings: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Add_profiles_to_an_opening: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Clone_job_opening: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Log_an_activity_in_job_opening: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Send_Emails_to_Client_contact_from_Job_Opening_page: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Filters_in_profile_search: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Save_search: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Load_search: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Delete_search: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  All_matches: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Best_matches: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],

  Change_status_from_active_to_closed: [
    'Admin',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  'Activity of a Job Opening': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  'Move from one stage to the other': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],

  'View candidate': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head'
  ],
  Recent_activity_view: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Upload_Files: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Download_Files: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Delete_Files: [
    'Admin',
    'Delivery Head',
  ],
  View_Files: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Download_candidate_Profiles_as_doc: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Edit_Candidate: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  'Archive candidate': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],

  Parse_resume: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Add_candidate_directly: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Add_candidate_from_Linkedin_scraper: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],

  Add_task: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Update_task_status: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Edit_a_Task_created_for_me_by_someone: [
    'Admin',
    'Sales Head',
    'Delivery Head',
  ],
  Edit_task: [
    'Admin',
  ],
  'Edit a task created by me': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Search_task: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  View_task_activity: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],

  Invite_Users: [
    'Admin',
  ],
  Edit_user: [
    'Admin',
  ],
  Active_Inactive_users: [
    'Admin',
  ],

  Add_job_category: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Edit_job_category: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  Delete_job_category: [
    'Admin'
  ],
  Active_or_Inactive_job_category: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  View_job_categories_in_dropdown: [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],

  'Send Emails to candidates': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  'View Emails': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  'Create Email templates': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],
  'Create Signature templates': [
    'Admin',
    'Recruiter',
    'Sales Rep',
    'Sales Head',
    'Delivery Head',
  ],

  Assign_Archive_Job_Openings: [
    'Admin',
    'Delivery Head',
  ],
  Assign_to_Recruiter_sales: [
    'Admin',
    'Delivery Head',
  ],
  // Assign_Recruiter_to_Openings: [
  //   'Admin',
  //   'Delivery Head',
  // ],
  // Assign_sales_to_Openings: [
  //   'Admin',
  //   'Sales Head',
  //   'Delivery Head',
  // ]
};

export default permissions;
