import constant from '../../helpers/Constants';

const baseInitialvalues = {
  id: '',
  // doc_id: '',
  created_user: '',
  created_ts: '',
  updated_user: '',
  updated_ts: '',
  first_name: '',
  last_name: '',
  middle_name: '',
  salutation: '',
  dob: '',
  nationality: '',
  name: '',
  headline: '',
  location: '',
  location_city: '',
  location_postcode: '',
  country: '',
  url: constant.RESUME_URL,
  links: '',
  resume_source: constant.RESUME_SOURCE,
  total_years_of_experience: '',
  skills: [{}],
  current_experience: {},
  experiences: [{}],
  educations: [{}],
  languages_known: [{}],
  contacts: {
    emails: '',
    mobile_numbers: '',
    home_numbers: '',
    fax_numbers: '',
    street_name: '',
    street_number_base: '',
    postal_code: '',
    city: '',
    region_code: '',
    region_code_description: '',
    country_code: '',
    country_code_description: ''
  },
  notice_period: 0,
  notice_period_type: '',
  curr_annual_salary: 0,
  curr_annual_salary_currency: '',
  exp_annual_salary: 0,
  exp_annual_salary_currency: '',
  curr_rate: 0,
  curr_rate_currency: '',
  curr_rate_type: '',
  exp_rate: 0,
  exp_rate_currency: '',
  exp_rate_type: '',
  reloc_possibility: '',
  pref_location: [],
  avail_start_date: '',
  avail_end_date: '',
  visas: [{}]
};

export default baseInitialvalues;
