const countries = {
  "Andorra": "ad",
  "United Arab Emirates": "ae",
  "Afghanistan": "af",
  "Antigua and Barbuda": "ag",
  "Anguilla": "ai",
  "Albania": "al",
  "Armenia": "am",
  "Netherlands Antilles": "an",
  "Angola": "ao",
  "Antarctica": "aq",
  "Argentina": "ar",
  "American Samoa": "as",
  "Austria": "at",
  "Australia": "au",
  "Aruba": "aw",
  "Azerbaidjan": "az",
  "Bosnia-Herzegovina": "ba",
  "Barbados": "bb",
  "Bangladesh": "bd",
  "Belgium": "be",
  "Burkina Faso": "bf",
  "Bulgaria": "bg",
  "Bahrain": "bh",
  "Burundi": "bi",
  "Benin": "bj",
  "Bermuda": "bm",
  "Brunei Darussalam": "bn",
  "Bolivia": "bo",
  "Brazil": "br",
  "Bahamas": "bs",
  "Bhutan": "bt",
  "Bouvet Island": "bv",
  "Botswana": "bw",
  "Belarus": "by",
  "Belize": "bz",
  "Canada": "ca",
  "Congo": "cg",
  "Switzerland": "ch",
  "Cook Islands": "ck",
  "Chile": "cl",
  "Cameroon": "cm",
  "China": "cn",
  "Colombia": "co",
  "Costa Rica": "cr",
  "Former Czechoslovakia": "cs",
  "Cuba": "cu",
  "Cape Verde": "cv",
  "Christmas Island": "cx",
  "Cyprus": "cy",
  "Czech Republic": "cz",
  "Germany": "de",
  "Djibouti": "dj",
  "Denmark": "dk",
  "Dominica": "dm",
  "Dominican Republic": "do",
  "Algeria": "dz",
  "Ecuador": "ec",
  "Estonia": "ee",
  "Egypt": "eg",
  "Western Sahara": "eh",
  "Eritrea": "er",
  "Spain": "es",
  "Ethiopia": "et",
  "Finland": "fi",
  "Fiji": "fj",
  "Falkland Islands": "fk",
  "Micronesia": "fm",
  "Faroe Islands": "fo",
  "France": "fr",
  "Gabon": "ga",
  "Great Britain": "gb",
  "Grenada": "gd",
  "Georgia": "ge",
  "French Guyana": "gf",
  "Ghana": "gh",
  "Gibraltar": "gi",
  "Greenland": "gl",
  "Gambia": "gm",
  "Guinea": "gn",
  "Greece": "gr",
  "Guatemala": "gt",
  "Guinea Bissau": "gw",
  "Guyana": "gy",
  "Hong Kong": "hk",
  "Heard and McDonald Islands": "hm",
  "Honduras": "hn",
  "Croatia": "hr",
  "Haiti": "ht",
  "Hungary": "hu",
  "Indonesia": "id",
  "Ireland": "ie",
  "Israel": "il",
  "India": "in",
  "British Indian Ocean Territory": "io",
  "Iraq": "iq",
  "Iran": "ir",
  "Iceland": "is",
  "Italy": "it",
  "Jamaica": "jm",
  "Jordan": "jo",
  "Japan": "jp",
  "Kenya": "ke",
  "Kyrgyzstan": "kg",
  "Cambodia": "kh",
  "Kiribati": "ki",
  "Comoros": "km",
  "Saint Kitts & Nevis Anguilla": "kn",
  "North Korea": "kp",
  "South Korea": "kr",
  "Kuwait": "kw",
  "Cayman Islands": "ky",
  "Kazakhstan": "kz",
  "Laos": "la",
  "Lebanon": "lb",
  "Saint Lucia": "lc",
  "Liechtenstein": "li",
  "Sri Lanka": "lk",
  "Liberia": "lr",
  "Lesotho": "ls",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Latvia": "lv",
  "Libya": "ly",
  "Morocco": "ma",
  "Monaco": "mc",
  "Moldavia": "md",
  "Madagascar": "mg",
  "Marshall Islands": "mh",
  "Macedonia": "mk",
  "Mali": "ml",
  "Myanmar": "mm",
  "Mongolia": "mn",
  "Macau": "mo",
  "Northern Mariana Islands": "mp",
  "Mauritania": "mr",
  "Montserrat": "ms",
  "Malta": "mt",
  "Mauritius": "mu",
  "Maldives": "mv",
  "Malawi": "mw",
  "Mexico": "mx",
  "Malaysia": "my",
  "Mozambique": "mz",
  "Namibia": "na",
  "Niger": "ne",
  "Norfolk Island": "nf",
  "Nigeria": "ng",
  "Nicaragua": "ni",
  "Netherlands": "nl",
  "Norway": "no",
  "Nepal": "np",
  "Nauru": "nr",
  "Neutral Zone": "nt",
  "Niue": "nu",
  "New Zealand": "nz",
  "Oman": "om",
  "Panama": "pa",
  "Peru": "pe",
  "Philippines": "ph",
  "Pakistan": "pk",
  "Poland": "pl",
  "Saint Pierre and Miquelon": "pm",
  "Pitcairn Island": "pn",
  "Puerto Rico": "pr",
  "Portugal": "pt",
  "Palau": "pw",
  "Paraguay": "py",
  "Qatar": "qa",
  "Romania": "ro",
  "Russian Federation": "ru",
  "Rwanda": "rw",
  "Saudi Arabia": "sa",
  "Solomon Islands": "sb",
  "Seychelles": "sc",
  "Sudan": "sd",
  "Sweden": "se",
  "Singapore": "sg",
  "Saint Helena": "sh",
  "Slovenia": "si",
  "Svalbard and Jan Mayen Islands": "sj",
  "Slovak Republic": "sk",
  "Sierra Leone": "sl",
  "San Marino": "sm",
  "Senegal": "sn",
  "Somalia": "so",
  "Suriname": "sr",
  "Saint Tome (Sao Tome) and Principe": "st",
  "Former USSR": "su",
  "El Salvador": "sv",
  "Syria": "sy",
  "Swaziland": "sz",
  "Turks and Caicos Islands": "tc",
  "Chad": "td",
  "French Southern Territories": "tf",
  "Togo": "tg",
  "Thailand": "th",
  "Tadjikistan": "tj",
  "Tokelau": "tk",
  "Turkmenistan": "tm",
  "Tunisia": "tn",
  "Tonga": "to",
  "East Timor": "tp",
  "Turkey": "tr",
  "Trinidad and Tobago": "tt",
  "Tuvalu": "tv",
  "Taiwan": "tw",
  "Tanzania": "tz",
  "Ukraine": "ua",
  "Uganda": "ug",
  "United Kingdom": "uk",
  "USA Minor Outlying Islands": "um",
  "United States": "us",
  "Uruguay": "uy",
  "Uzbekistan": "uz",
  "Vatican City State": "va",
  "Saint Vincent & Grenadines": "vc",
  "Venezuela": "ve",
  "Vietnam": "vn",
  "Vanuatu": "vu",
  "Wallis and Futuna Islands": "wf",
  "Samoa": "ws",
  "Yemen": "ye",
  "Mayotte": "yt",
  "Yugoslavia": "yu",
  "South Africa": "za",
  "Zambia": "zm",
  "Zaire": "zr",
  "Zimbabwe": "zw"
};

export default countries;